[package]
name = "gh-actions-lint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Lints GitHub Actions workflows for what they get away with but did not mean"

[dependencies]
gh-actions-spec.workspace = true
gh-actions-context.workspace = true
gh-actions-expr.workspace = true
gh-actions-plan.workspace = true
yaml-with-spans.workspace = true
