[package]
name = "canopy-tests"
version.workspace = true
edition.workspace = true
publish = false

[[test]]
name = "integration"
path = "integration.rs"

[dependencies]
local-runner.workspace = true
gh-actions-runner.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
serde_json = "1.0"

