[package]
name = "gh-actions-spec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The GitHub Actions workflow and action.yml file formats, as types"

[dependencies]
indexmap = { version = "2.14.0", features = ["serde"] }
serde.workspace = true

[dev-dependencies]
yaml-with-spans.workspace = true
